version: '3.8'
services:
  
  supermicro-java-ikvm:
    image: supermicro-java-ikvm
    container_name: supermicro-java-ikvm
    environment:
      TZ: UTC
      KVM_HOST: # IP or Hostname
      KVM_USER: # Your IPMI Username
      KVM_PASS: # Your IPMI Password
      DISPLAY_WIDTH: 1024 # Display Width
      DISPLAY_HEIGHT: 768 # Display Height
    ports:
      - 5800:5800 # Web UI Port
      - 5900:5900 # VNC Port
    volumes:
      - ./vmedia:/app/vmedia/ # Virtual Media ISO's
      - ./screenshots:/app/screenshots/ # Screenshots / Recordings
      - supermicro-java-ikvm:/config/ # Persistent Configuration for user preferences
    restart: no

volumes:
  supermicro-java-ikvm:
    name: supermicro-java-ikvm
